---
- name: solr | create conf directory
  file: dest=/var/lib/solr/{{ item.name }}/conf state=directory owner=jetty group=root mode=0750
  with_items: "{{ solr_cores }}"
  when: not item.delete|default(False)
  notify: restart solr-jetty
  tags: ['solr']

- name: solr | rsync conf
  shell: rsync -a /etc/solr/conf/ /var/lib/solr/{{ item.name }}/conf/ creates=/var/lib/solr/{{ item.name }}/conf/solrconfig.xml
  with_items: "{{ solr_cores }}"
  when: not item.delete|default(False)
  notify: restart solr-jetty
  tags: ['solr']

- name: solr | link core
  file: src=/var/lib/solr/{{ item.name }} dest=/usr/share/solr/{{ item.name }} state=link
  with_items: "{{ solr_cores }}"
  when: item.name|default(False) and not item.delete|default(False)
  notify: restart solr-jetty
  tags: ['solr']
