---
- name: databases | delete databases
  mysql_db: name={{ item.name }} state=absent
  with_items: "{{ databases }}"
  when: item.delete|default(False)

- name: databases | delete local users
  mysql_user: name={{ item.name }} password={{ item.pass }} priv={{ item.name }}.*:ALL append_privs=true state=absent
  with_items: "{{ databases }}"
  when: item.ip is not defined and item.delete|default(False)

- name: databases | delete remote users
  mysql_user: name={{ item.name }} password={{ item.pass }} host='%' priv={{ item.name }}.*:ALL state=absent append_privs=yes
  with_items: "{{ databases }}"
  when: item.ip is defined and item.delete|default(False)

- name: databases | delete ufw rules for these special databases
  ufw: rule=allow interface={{ public_interface }} direction=in proto=tcp src={{ item.ip }} to_port=3306 delete=yes
  with_items: "{{ databases }}"
  when: item.ip is defined and item.delete|default(False)
  notify: reload ufw
