---

- apt: name=icinga2-classicui state=installed
  notify: restart apache2

- name: Icinga Classic UI requires the StatusDataWriter, CompatLogger and ExternalCommandListener
  shell: command="icinga2 feature enable statusdata compatlog command" creates=/etc/icinga2/features-enabled/compatlog.conf
  notify: restart icinga

- name: Install icinga2-classicui
  apt: name=icinga2-classicui state=installed
  notify: restart apache2

- name: Put htpasswd users
  template: src=htpasswd.users dest=/etc/icinga2-classicui/htpasswd.users owner=root group=www-data mode=640

- name: Put cgi.cfg
  template: src=classic-cgi.cfg dest=/etc/icinga2-classicui/cgi.cfg owner=root group=root mode=644
  notify: restart icinga
