---
- name: copy over munin plugins
  copy: src=solr/{{ item }} dest=/usr/share/munin/plugins/{{ item }} mode=0755 owner=root group=root
  with_items:
    - solr
    - solrmulticore

- name: enable munin plugin {{ item }}
  file: src=/usr/share/munin/plugins/{{ item }} dest=/etc/munin/plugins/{{ item }} state=link
  with_items:
    - solr
    - solrmulticore
  notify: restart munin-node

- name: put solr check
  template: src=solr/solr.conf.j2 dest=/etc/icinga2/conf.d/solr.conf mode=0644
  notify: restart icinga2 and update master config
