---
# Icingaweb2 manual setup steps taken from
# https://github.com/Icinga/icingaweb2/blob/master/doc/installation.md

- name: make sure required packages are installed
  apt: name={{ item }} state=installed
  with_items:
    - php5-common
    - php5
    - php-pear
    - php5-fpm
    - php5-curl
    - php5-dev
    - php5-gd
    - php5-mysql
    - php5-imagick
    - php5-intl
    - icingaweb2
    - icinga2-ido-mysql
  register: icinstall

- name: enable php module
  shell: php5enmod {{ item }} creates=/etc/php5/apache2/conf.d/20-{{ item }}.ini
  with_items:
    - imagick
    - intl
  notify: restart apache2

- name: enable ido-mysql and command feature for web
  shell: icinga2 feature enable {{ item }} creates=/etc/icinga2/features-enabled/{{ item }}.conf
  with_items:
    - ido-mysql
    - command
  when: icinstall.changed

- name: create icingaweb2 database
  mysql_db: name={{ webdbname }} state=present
  register: webdb

- name: create icingaweb2 database user
  mysql_user: name={{ webdbuser }} password={{ webdbpass }} priv={{ webdbname }}.*:ALL append_privs=true state=present

- name: load database schema
  mysql_db: state=import name={{ webdbname }} target=/usr/share/icingaweb2/etc/schema/mysql.schema.sql
  when: webdb.changed

- name: create users in database
  command: >
    mysql --user={{ webdbuser }} --password={{ webdbpass }} {{ webdbname }}
    --batch --skip-column-names
    --execute="INSERT INTO icingaweb_user (name, active, password_hash) VALUES ('{{ item.name }}', 1, '{{ item.pass }}') ON DUPLICATE KEY UPDATE name='{{ item.name }}', password_hash='{{ item.pass }}'"
  with_items: "{{ webusers }}"
  tags: ['users']

- name: put configuration templates
  template: src={{ item }}.j2 dest=/etc/icingaweb2/{{ item }} owner=www-data group=icingaweb2 mode=0660
  with_items:
    - authentication.ini
    - config.ini
    - resources.ini
    - roles.ini

- name: create monitoring module basedirs
  file: dest={{ item }} state=directory owner=www-data group=icingaweb2 mode=0775
  with_items:
    - /etc/icingaweb2/modules/monitoring
    - /etc/icingaweb2/enabledModules

- name: put monitoring module configuration
  template: src=modules/monitoring/{{ item }}.j2 dest=/etc/icingaweb2/modules/monitoring/{{ item }} owner=www-data group=icingaweb2 mode=0644
  with_items:
    - backends.ini
    - commandtransports.ini
    - config.ini

- name: enable monitoring module
  file: src=/usr/share/icingaweb2/modules/monitoring dest=/etc/icingaweb2/enabledModules/monitoring state=link
  notify: restart apache2
