---
- name: set apt preferences
  copy:
    src: preferences.conf
    dest: /etc/apt/preferences.d/php-preferences
    owner: root
    group: root
    mode: "0644"

- name: install apt-transport-https
  apt:
    name: apt-transport-https
    state: present

- apt_key:
    url: "https://packages.sury.org/php/apt.gpg"
    state: present

- name: add sury repo
  apt_repository:
    repo: "deb https://packages.sury.org/php/ {{ ansible_distribution_release }} main"
    update_cache: yes
