---
- name: install memcached
  apt:
    name:
      - memcached
      - libcache-memcached-perl
      - munin-plugins-extra
    state: present
    cache_valid_time: 3600
    update_cache: yes
  notify: start memcached

- name: put memcached config file
  template:
    src: memcached.conf.j2
    dest: /etc/memcached.conf
    owner: root
    group: root
    mode: "0644"
  notify: restart memcached
