- name: Install owncloud env.
  hosts: all:!infra
  become: True

  pre_tasks:
    - include_vars: "./os_vars/{{ ansible_distribution_release }}.yml"
      tags: ['owncloud']
    - include_vars: "./../inventory/{{ platform }}/inventory/group_vars/{{ item }}.yml"
      with_items:
        - owners
      tags: ['glue','glue_owner_keys']
    - apt: update_cache=yes cache_valid_time=3600

  roles:
    - role: owncloud
      tags: ['owncloud']
